### PR TITLE
Restored product name

### PR DESCRIPTION
**Pull request by sachitrajbhandari**

### CODE REVIEW

**Review by alexgleith — APPROVED** [review]

**Comment by sachitrajbhandari** [comment]
@jeremyh, EO3-nbart product set need to be removed from test?

**Review by alexgleith — APPROVED** [review]
I can't really comment on removing the AWS products from the tests... but otherwise it looks fine.

**Comment by sachitrajbhandari** [comment]
> I can't really comment on removing the AWS products from the tests... but otherwise it looks fine.

@jeremyh, Could you please provide feedback on removal of EO3-nbart product set from test?

**Comment by jeremyh** [comment]
> > I can't really comment on removing the AWS products from the tests... but otherwise it looks fine.
> 
> @jeremyh, Could you please provide feedback on removal of EO3-nbart product set from test?

The tests blindly try to add all products under the glob `products/*.odc-product.yaml`, which is now
a problem because we now have two conflicting products that can't be added to the same datacube.

I'd probably fix it by either

1. Creating a separate directory for environment-specific products like this. They wont be found/added by the default test framework.
2. Use the same folder, but a different naming convention for whatever we want to call these things (env-products? sub-products?) and exclude those by the default in the tester.

I'd probably lean toward the first option. Perhaps a layout like this?
```
.
├── environment-specific
│   └── aws
│       └── products
│           ├── nbart_ls5.odc-product.yaml
│           ├── nbart_ls7.odc-product.yaml
│           └── nbart_ls8.odc-product.yaml
└── products
    ├── ard_ls5.odc-product.yaml
    ├── ard_ls7.odc-product.yaml
    ├── ard_ls8.odc-product.yaml
    ├── l1_ls5_ga.odc-product.yaml
    ├── l1_ls5.odc-product.yaml
    ├── l1_ls7_ga.odc-product.yaml
    ├── l1_ls7.odc-product.yaml
    ├── l1_ls8_ga.odc-product.yaml
    └── l1_ls8.odc-product.yaml
```

**Comment by jeremyh** [comment]
I'd like to reorgnise the configs even further than that, though it should go into a separate issue. That layout would at least let us merge this now without conflicting with other open PRs.

**Review by jeremyh — COMMENTED** [review]
(marking as reviewed: see above comment)

**Comment by sachitrajbhandari** [comment]
> I'd like to reorgnise the configs even further than that, though it should go into a separate issue. That layout would at least let us merge this now without conflicting with other open PRs.

The new directory `products-aws` has been created as below for aws-specific products which follows your first option and excluded by the default test framework. Thanks for your feedback and suggestions. 

```
.
├── products-aws
│     ├── ard_ls5.odc-product.yaml
│     ├── ard_ls7.odc-product.yaml
│     └── ard_ls8.odc-product.yaml
└── products
    ├── ard_ls5.odc-product.yaml
    ├── ard_ls7.odc-product.yaml
    ├── ard_ls8.odc-product.yaml
    ├── l1_ls5_ga.odc-product.yaml
    ├── l1_ls5.odc-product.yaml
    ├── l1_ls7_ga.odc-product.yaml
    ├── l1_ls7.odc-product.yaml
    ├── l1_ls8_ga.odc-product.yaml
    └── l1_ls8.odc-product.yaml
```

**Pull request merged**
