### PR TITLE
[Do not merge] Adding support for ODC datacube-qgis plugin.

### PR DESCRIPTION
**Pull request by lpinner**
This PR adds support for the ODC [datacube-qgis](https://github.com/opendatacube/datacube-qgis) plugin.  

**Note:**
PR is for review/discussion only at this stage as it can't be merged until QGIS 3.0 has been packaged by conda-forge ([qgis-feedstock/issues/17](https://github.com/conda-forge/qgis-feedstock/issues/17)) which they are having some difficulties doing.  I'm opening this PR now in case you need any changes made as I only have a couple of days left before I leave.

**Changes:**
 - Add the QGIS package to the dea-env module
 - Add plugin installation and setup to the dea module  
 - Modified build_environment_module.py and modulespec.yaml to handle multiple pip calls (i.e one for ----prefix and another for --target).

### CODE REVIEW

**Comment by lpinner** [comment]
Last day at GA today : (

Any comments?

**Comment by omad** [comment]
Hi Luke, sorry I hadn't replied here, we'd only discussed in person.

These changes all look great to me. Unfortunately we're still waiting for a stable qgis3 build to make it into `conda-forge`. As soon as that happens I'll merge this and include QGIS + your plugin in the NCI environment.

**Comment by lpinner** [comment]
No problem, I was just getting antsy as I didn't want to leave it to the last minute to make changes if you needed them.

**Comment by omad** [comment]
We still don't have qgis running well from conda. Closing for now.

**Comment by lpinner** [comment]
@omad  I mucked around for ages earlier this year trying to get QGIS to work with dea & dea-env modules and kept running into dependency issues.  However, it works nicely (and I'm using it frequently personally) as a separate QGIS+datacube conda env and could probably be packaged as a separate module fairly easily.

**Pull request closed without merging**
