### PR TITLE
Changed name: GeoTiff to GeoTIFF for ls8_pq_legacy_scene and ls8_pq_l…

### PR DESCRIPTION
**Pull request by ashoka1234**
…egacy_oli_scene

### CODE REVIEW

**Comment by omad** [comment]
Sorry I didn't get to this sooner Ashoka!

Should this change be for *all* of the Products? We want the configuration in this repo to match what's being produced on disk as well as what's in the database...

**Comment by ashoka1234** [comment]
No this change is not product wide. Unfortunately there is no consistency in the usage of GeoTiff and GeoTIFF names in the code, database, docs and configs. At the time we only used the more formal name ,GeoTIFF, for newly added products, i.e. pq legacy scene products (ls{8,7,5}_pq_legacy_scene, I missed ls8_pq_legacy_oli_scene however). I would think libraries probably use the formal name GeoTIFF.

**Comment by jeremyh** [comment]
These are the current NCI products, the new pq_legacy is the only one with "GeoTIFF":

```
             name             │ platform  │ format  │ instrument │       product_type
══════════════════════════════╪═══════════╪═════════╪════════════╪══════════════════════════
 ls5_fc_albers                │ LANDSAT_5 │ NetCDF  │ TM         │ fractional_cover
 ls5_level1_scene             │ LANDSAT_5 │ GeoTiff │ TM         │ level1
 ls5_nbar_albers              │ LANDSAT_5 │ NetCDF  │ TM         │ nbar
 ls5_nbar_scene               │ LANDSAT_5 │ GeoTiff │ TM         │ nbar
 ls5_nbart_albers             │ LANDSAT_5 │ NetCDF  │ TM         │ nbart
 ls5_nbart_scene              │ LANDSAT_5 │ GeoTiff │ TM         │ nbart
 ls5_pq_albers                │ LANDSAT_5 │ NetCDF  │ TM         │ pqa
 ls5_pq_legacy_scene          │ LANDSAT_5 │ GeoTIFF │ TM         │ legacy_pqa
 ls5_pq_scene                 │ LANDSAT_5 │ GeoTiff │ TM         │ pqa
 ls5_satellite_telemetry_data │ LANDSAT_5 │ ¤       │ TM         │ satellite_telemetry_data
 ls7_fc_albers                │ LANDSAT_7 │ NetCDF  │ ETM        │ fractional_cover
 ls7_fc_albers_staging        │ LANDSAT_7 │ NetCDF  │ ETM        │ fractional_cover
 ls7_level1_scene             │ LANDSAT_7 │ GeoTiff │ ETM        │ level1
 ls7_nbar_albers              │ LANDSAT_7 │ NetCDF  │ ETM        │ nbar
 ls7_nbar_scene               │ LANDSAT_7 │ GeoTiff │ ETM        │ nbar
 ls7_nbart_albers             │ LANDSAT_7 │ NetCDF  │ ETM        │ nbart
 ls7_nbart_scene              │ LANDSAT_7 │ GeoTiff │ ETM        │ nbart
 ls7_pq_albers                │ LANDSAT_7 │ NetCDF  │ ETM        │ pqa
 ls7_pq_legacy_scene          │ LANDSAT_7 │ GeoTIFF │ ETM        │ legacy_pqa
 ls7_pq_scene                 │ LANDSAT_7 │ GeoTiff │ ETM        │ pqa
 ls7_satellite_telemetry_data │ LANDSAT_7 │ ¤       │ ETM        │ satellite_telemetry_data
 ls8_fc_albers                │ LANDSAT_8 │ NetCDF  │ OLI_TIRS   │ fractional_cover
 ls8_level1_oli_scene         │ LANDSAT_8 │ GeoTiff │ OLI        │ level1
 ls8_level1_scene             │ LANDSAT_8 │ GeoTiff │ OLI_TIRS   │ level1
 ls8_nbar_albers              │ LANDSAT_8 │ NetCDF  │ OLI_TIRS   │ nbar
 ls8_nbar_oli_albers          │ LANDSAT_8 │ NetCDF  │ OLI        │ nbar
 ls8_nbar_oli_scene           │ LANDSAT_8 │ GeoTiff │ OLI        │ nbar
 ls8_nbar_scene               │ LANDSAT_8 │ GeoTiff │ OLI_TIRS   │ nbar
 ls8_nbart_albers             │ LANDSAT_8 │ NetCDF  │ OLI_TIRS   │ nbart
 ls8_nbart_oli_albers         │ LANDSAT_8 │ NetCDF  │ OLI        │ nbart
 ls8_nbart_oli_scene          │ LANDSAT_8 │ GeoTiff │ OLI        │ nbart
 ls8_nbart_scene              │ LANDSAT_8 │ GeoTiff │ OLI_TIRS   │ nbart
 ls8_pq_albers                │ LANDSAT_8 │ NetCDF  │ OLI_TIRS   │ pqa
 ls8_pq_legacy_oli_scene      │ LANDSAT_8 │ GeoTiff │ OLI        │ legacy_pqa
 ls8_pq_legacy_scene          │ LANDSAT_8 │ GeoTIFF │ OLI_TIRS   │ legacy_pqa
 ls8_pq_oli_scene             │ LANDSAT_8 │ GeoTiff │ OLI        │ pqa
 ls8_pq_scene                 │ LANDSAT_8 │ GeoTiff │ OLI_TIRS   │ pqa
 ls8_satellite_telemetry_data │ LANDSAT_8 │ ¤       │ ¤          │ satellite_telemetry_data
(38 rows)
```
`GeoTiff` isn't perfect, but we were pretty consistent with it before.

**Comment by jeremyh** [comment]
Btw, we’re battling similar product inconsistencies within new ARD products at the moment —  we’ve started making a DEA jsonschema to catch trivial differences like this in the future.

**Comment by ashoka1234** [comment]
Yes @jeremyh that is the case. I think the all lowercase 'geotiff' could be considered a variant.

**Review by omad — APPROVED** [review]

**Comment by omad** [comment]
I've updated the capitalisation of the rest of the product definitions in this repo, and have also updated the products in the production database.

# Production Database Listing
```sql
select name, metadata->'format'->'name' format from dataset_type;

--------------------------------+-----------
             name               | format
--------------------------------+-----------
 ls5_satellite_telemetry_data   | ¤
 pq_count_annual_summary        | "NetCDF"
 low_tide_comp_count            | "NetCDF"
 ls5_nbart_scene                | "GeoTIFF"
 ls5_pq_scene                   | "GeoTIFF"
 ls7_satellite_telemetry_data   | ¤
 ls7_nbar_scene                 | "GeoTIFF"
 srtm_dem1sv1_0                 | "AIG"
 ls8_satellite_telemetry_data   | ¤
 ls7_nbart_scene                | "GeoTIFF"
 ls8_nbar_scene                 | "GeoTIFF"
 pq_count_summary               | "NetCDF"
 ls8_level1_scene               | "GeoTIFF"
 ls8_nbart_scene                | "GeoTIFF"
 gamma_ray                      | "NETCDF"
 high_tide_comp_20p             | "NetCDF"
 ls5_nbar_albers                | "NetCDF"
 wofs_modified_albers2_archived | "NetCDF"
 ls7_fc_albers_staging          | "NetCDF"
 high_tide_comp_count           | "NetCDF"
 bom_rainfall_grids             | "NETCDF"
 dsm1sv10                       | "GeoTIFF"
 ls8_level1_oli_scene           | "GeoTIFF"
 ls8_nbar_oli_scene             | "GeoTIFF"
 low_tide_comp_20p              | "NetCDF"
 ls8_nbart_oli_scene            | "GeoTIFF"
 item_v2_conf                   | "NetCDF"
 item_v2                        | "NetCDF"
 ls5_fc_albers                  | "NetCDF"
 ls5_level1_scene               | "GeoTIFF"
 ls5_nbar_scene                 | "GeoTIFF"
 ls7_level1_scene               | "GeoTIFF"
 ls7_pq_scene                   | "GeoTIFF"
 ls8_pq_scene                   | "GeoTIFF"
 ls7_fc_albers                  | "NetCDF"
 ls8_fc_albers                  | "NetCDF"
 ls8_pq_oli_scene               | "GeoTIFF"
 ls5_nbart_albers               | "NetCDF"
 ls8_nbar_albers                | "NetCDF"
 ls7_nbar_albers                | "NetCDF"
 ls8_nbar_oli_albers            | "NetCDF"
 ls8_nbart_oli_albers           | "NetCDF"
 ls8_nbart_albers               | "NetCDF"
 ls7_nbart_albers               | "NetCDF"
 ls8_pq_albers                  | "NetCDF"
 ls5_pq_albers                  | "NetCDF"
 ls7_pq_albers                  | "NetCDF"
 ls8_pq_legacy_scene            | "GeoTIFF"
 ls8_pq_legacy_oli_scene        | "GeoTIFF"
```


<details><summary>Update process here</summary>


# Dump Definitions for all the products
```bash
product_list=$(datacube product list -f csv | csvcut -c name - | tail -n +2)

for prod in $product_list; do
    datacube product show $prod > $prod.yaml
done
```
# Collect the ones we want to modify
```bash
mkdir to_mod
mv $(grep -l GeoTiff *) to_mod/
cd to_mod
```
# Modify the definitions
```bash
sed -i 's/GeoTiff/GeoTIFF/' *
```

# Check what changes will be made
```bash
datacube -v product update *
```

# Make the changes in the Index
```bash
datacube -v product update --alow-unsafe *
```

# Logged Update Output
```
2018-06-15 10:58:00,199 13008 datacube INFO Running datacube command: /g/data/v10/public/modules/dea/20180515/bin/datacube -v product update ls5_level1_scene.yaml ls5_nbar_scene.yaml ls5_nbart_scene.yaml ls5_pq_scene.yaml ls7_level1_scene.yaml ls7_nbar_scene.yaml ls7_nbart_scene.yaml ls7_pq_scene.yaml ls8_level1_oli_scene.yaml ls8_level1_scene.yaml ls8_nbar_oli_scene.yaml ls8_nbar_scene.yaml ls8_nbart_oli_scene.yaml ls8_nbart_scene.yaml ls8_pq_legacy_oli_scene.yaml ls8_pq_oli_scene.yaml ls8_pq_scene.yaml
2018-06-15 10:58:00,896 13008 datacube.index._products INFO No changes detected for product ls5_level1_scene
Updated "ls5_level1_scene"
2018-06-15 10:58:00,975 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls5_nbar_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,044 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls5_nbart_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,060 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls5_pq_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,073 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls7_level1_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,146 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls7_nbar_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,222 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls7_nbart_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,239 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls7_pq_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,251 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_level1_oli_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,264 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_level1_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,334 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_nbar_oli_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,405 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_nbar_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,483 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_nbart_oli_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,556 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_nbart_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,573 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_pq_legacy_oli_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,589 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_pq_oli_scene": Unsafe changes at metadata.format.name
2018-06-15 10:58:01,606 13008 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
Failed to update "ls8_pq_scene": Unsafe changes at metadata.format.name
dra547@raijin4:~/updating_products_tiff_capitalisation/to_mod $ datacube -v product update --allow-unsafe *
2018-06-15 10:58:23,773 13729 datacube INFO Running datacube command: /g/data/v10/public/modules/dea/20180515/bin/datacube -v product update --allow-unsafe ls5_level1_scene.yaml ls5_nbar_scene.yaml ls5_nbart_scene.yaml ls5_pq_scene.yaml ls7_level1_scene.yaml ls7_nbar_scene.yaml ls7_nbart_scene.yaml ls7_pq_scene.yaml ls8_level1_oli_scene.yaml ls8_level1_scene.yaml ls8_nbar_oli_scene.yaml ls8_nbar_scene.yaml ls8_nbart_oli_scene.yaml ls8_nbart_scene.yaml ls8_pq_legacy_oli_scene.yaml ls8_pq_oli_scene.yaml ls8_pq_scene.yaml
2018-06-15 10:58:24,481 13729 datacube.index._products INFO No changes detected for product ls5_level1_scene
Updated "ls5_level1_scene"
2018-06-15 10:58:24,560 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:24,560 13729 datacube.index._products INFO Updating product ls5_nbar_scene
Updated "ls5_nbar_scene"
2018-06-15 10:58:24,690 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:24,690 13729 datacube.index._products INFO Updating product ls5_nbart_scene
Updated "ls5_nbart_scene"
2018-06-15 10:58:24,758 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:24,758 13729 datacube.index._products INFO Updating product ls5_pq_scene
Updated "ls5_pq_scene"
2018-06-15 10:58:24,814 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:24,814 13729 datacube.index._products INFO Updating product ls7_level1_scene
Updated "ls7_level1_scene"
2018-06-15 10:58:24,941 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:24,941 13729 datacube.index._products INFO Updating product ls7_nbar_scene
Updated "ls7_nbar_scene"
2018-06-15 10:58:25,063 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,064 13729 datacube.index._products INFO Updating product ls7_nbart_scene
Updated "ls7_nbart_scene"
2018-06-15 10:58:25,131 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,131 13729 datacube.index._products INFO Updating product ls7_pq_scene
Updated "ls7_pq_scene"
2018-06-15 10:58:25,185 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,185 13729 datacube.index._products INFO Updating product ls8_level1_oli_scene
Updated "ls8_level1_oli_scene"
2018-06-15 10:58:25,258 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,258 13729 datacube.index._products INFO Updating product ls8_level1_scene
Updated "ls8_level1_scene"
2018-06-15 10:58:25,394 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,394 13729 datacube.index._products INFO Updating product ls8_nbar_oli_scene
Updated "ls8_nbar_oli_scene"
2018-06-15 10:58:25,513 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,513 13729 datacube.index._products INFO Updating product ls8_nbar_scene
Updated "ls8_nbar_scene"
2018-06-15 10:58:25,692 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,692 13729 datacube.index._products INFO Updating product ls8_nbart_oli_scene
Updated "ls8_nbart_oli_scene"
2018-06-15 10:58:25,810 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,810 13729 datacube.index._products INFO Updating product ls8_nbart_scene
Updated "ls8_nbart_scene"
2018-06-15 10:58:25,876 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,876 13729 datacube.index._products INFO Updating product ls8_pq_legacy_oli_scene
Updated "ls8_pq_legacy_oli_scene"
2018-06-15 10:58:25,931 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,932 13729 datacube.index._products INFO Updating product ls8_pq_oli_scene
Updated "ls8_pq_oli_scene"
2018-06-15 10:58:25,987 13729 datacube.index._products INFO Unsafe change in metadata.format.name from 'GeoTiff' to 'GeoTIFF'
2018-06-15 10:58:25,987 13729 datacube.index._products INFO Updating product ls8_pq_scene
Updated "ls8_pq_scene"
```
</details>

**Pull request merged**
