### PR TITLE
Add USGS C2 L1 product definition

### PR DESCRIPTION
**Pull request by jeremyh**
It passes eo3-validate against the test dataset that @dunkgray added to eodataset3, though I haven't tested data loading.

### CODE REVIEW

**Comment by jeremyh** [comment]
(And I assume the data is still CC-BY-4.0 licensed, right?)

**Comment by dunkgray** [comment]
RE (And I assume the data is still CC-BY-4.0 licensed, right?) Good assumption.  I googled around and I could not find any licensing info.

**Review by dunkgray — APPROVED** [review]

**Comment by dunkgray** [comment]
Hi Jeremy,
Could you add the product name to this test - integration_tests/test_config.py, so they pass and this can be merged.  Thanks!

**Comment by dunkgray** [comment]
Thanks! Are you ok with me merging this now?

**Pull request merged**
