### PR TITLE
Add instructions on accessing the sandbox

### PR DESCRIPTION
**Pull request by caitlinadams**
Also includes a restructure of the "Connect" section of the docs, now labelled as "Setup". 

Leaving as a draft request for now, since it's not yet appropriate to have this content deployed, but it should be reviewed.

### CODE REVIEW

**Comment by caitlinadams** [comment]
@omad and @robbibt -- I'm adding this as a draft PR so we can have some discussions around it during the Notebook working group meeting on Thursday.

**Comment by omad** [comment]
Awesome! I'll have a closer read before Thursday. Thanks :)

**Comment by robbibt** [comment]
@caitlinadams Is this still an active PR? I suspect we covered this in the User Guide updates in https://github.com/GeoscienceAustralia/dea-docs

**Comment by caitlinadams** [comment]
Hey @robbibt, I don't think so -- I think this all got handled when I got access to the main repo and stopped working with a fork. I'll close this now.

**Pull request closed without merging**
