### PR TITLE
created new eo3 type

### PR DESCRIPTION
**Pull request by kieranricardo**
Adds a new metadata type that contains the standard eo3 fields plus the searchable fields here: https://explorer.sandbox.dea.ga.gov.au/products/s2a_ard_granule

### CODE REVIEW

**Comment by alexgleith** [comment]
Can we not just use the Landsat one? https://github.com/GeoscienceAustralia/digitalearthau/blob/develop/digitalearthau/config/eo3/eo3_landsat_ard.odc-type.yaml

**Comment by kieranricardo** [comment]
the Landsat one has a bunch of extra fields - is that important? Do searchable fields have to exist in dataset documents?

**Comment by alexgleith** [comment]
Nope, extra fields is fine. No problem with that...

Let's re-use it :-)

**Comment by kieranricardo** [comment]
sounds good :)

**Comment by alexgleith** [comment]
I'm happy if @omad is happy!

**Review by omad — APPROVED** [review]
LGTM!

I'm sad about the poor naming, but I'll get over it and we can consider fixing it some other time. :)

**Pull request merged**
