### PR TITLE
Increase the allowed cache age to 23hrs

### LINKED ISSUE #201: FileExistsError: dea-sync
When two or more `dea-sync` jobs run at the same time for a given product, these `sync` try to access the same `cache` file and reports following error.

```
Traceback (most recent call last):
  File "/g/data/v10/public/modules/dea/20181213/bin/dea-sync", line 11, in <module>
    sys.exit(cli())
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/datacube/ui/click.py", line 190, in new_func
    return f(parsed_config, *args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/datacube/ui/click.py", line 218, in with_index
    return f(index, *args, **kwargs)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/__init__.py", line 95, in cli
    **fix_settings
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/fixes.py", line 108, in fix_mismatches
    for mismatch in mismatches:
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/__init__.py", line 163, in get_mismatches
    workers=job_count
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/scan.py", line 154, in mismatches_for_collection
    path_dawg = build_pathset(collection, cache_folder, log=log)
  File "/g/data/v10/public/modules/dea/20181213/lib/python3.6/site-packages/digitalearthau/sync/scan.py", line 69, in build_pathset
    with fileutils.atomic_save(str(locations_cache)) as f:
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 429, in __enter__
    self.setup()
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 425, in setup
    self._open_part_file()
  File "/g/data/v10/public/modules/dea-env/20181015/lib/python3.6/site-packages/boltons/fileutils.py", line 390, in _open_part_file
    fd = os.open(self.part_path, self.open_flags, file_perms)
FileExistsError: [Errno 17] File exists: '/g/data/v10/work/sync/ls5_pq_scene/2018-12-24T1112/cache/product_ls5_pq_scene/locations.dawg.part'
```

### PR DESCRIPTION
**Pull request by santoshamohan**
# Reason for this pull request
Multiple `dea-sync` jobs for a given product try to access the same `cache` file, after the `cache` age time has elapsed. 

# Proposed solution
Increase `cache` file age to 24 hours from 12 hours. This would give sufficient time while the jobs wait for execution in the `pbs` queue.

- Fixes #201

### CODE REVIEW

**Comment by jeremyh** [comment]
How often are these jobs triggered? 

If it's every 24 hours, it would be better to have a 23hour timeout, so that the submitter regenerates the (expired) cache every time. Otherwise the cache might expire _just_ after submission, and we'll make the problem worse.

**Comment by jeremyh** [comment]
(see discussion on origin issue: https://github.com/GeoscienceAustralia/digitalearthau/issues/201#issuecomment-463041371)

**Comment by santoshamohan** [comment]
Thanks Jeremy. I will change the timeout to be 23hrs.

**Review by jeremyh — APPROVED** [review]
:+1:

**Pull request merged**
